const C=25,S=24,canvas=document.getElementById("game"),ctx=canvas.getContext("2d");
const $=id=>document.getElementById(id);let snake,food,power=null,dir={x:1,y:0},next={x:1,y:0},score=0,level=1,coins=0,running=false,paused=false,last=0,acc=0,diff="Medium",sound=true,runs=+localStorage.runs||0,xp=+localStorage.xp||0,best=+localStorage.neonBest||0;
const speeds={Easy:240,Medium:210,Hard:175,Insane:145},themes=[
["Cyber Neon","#00f3ff","#070b14","#ff007f"],["Matrix","#39ff14","#051408","#a855f7"],["Galaxy","#c084fc","#0d0b1e","#f43f5e"],["Inferno","#ff4500","#140707","#eab308"],["Arctic","#38bdf8","#09131a","#ff467e"]];let ti=0;let leaderboard=JSON.parse(localStorage.neonLeaderboard||"[]");
$("best").textContent=String(best).padStart(4,"0");$("xp").textContent=xp;$("runs").textContent=runs;renderLeaderboard();
function setTheme(){let t=themes[ti];document.documentElement.style.setProperty("--accent",t[1]);document.documentElement.style.setProperty("--bg",t[2]);document.documentElement.style.setProperty("--pink",t[3]);}
function renderLeaderboard(){const el=$("leaderboard");if(!el)return;el.innerHTML=leaderboard.slice(0,5).map((v,i)=>`<div class="leaderboard-row"><b>${i+1}</b><span>${v.diff}</span><strong>${String(v.score).padStart(4,"0")}</strong></div>`).join("")||"<div class=\"leaderboard-row\"><span>First run</span><strong>----</strong></div>"}
function saveRun(){if(score<=0)return;leaderboard.push({score,diff,date:Date.now()});leaderboard.sort((a,b)=>b.score-a.score);leaderboard=leaderboard.slice(0,5);localStorage.neonLeaderboard=JSON.stringify(leaderboard);renderLeaderboard()}
function beep(freq=440,d=0.05){if(!sound)return;try{let a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;o.type="square";g.gain.value=.025;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+d)}catch(e){}}
function reset(){snake=[{x:12,y:12},{x:11,y:12},{x:10,y:12}];dir={x:1,y:0};next={x:1,y:0};score=0;level=1;coins=0;power=null;spawnFood();update();draw()}
function spawnFood(){do{food={x:Math.floor(Math.random()*C),y:Math.floor(Math.random()*C),type:Math.random()<.08?"gold":Math.random()<.13?"power":"normal"}}while(snake.some(p=>p.x===food.x&&p.y===food.y))}
function spawnPower(){let types=["OVERDRIVE","SHIELD","MAGNET","GHOST"];do{power={x:Math.floor(Math.random()*C),y:Math.floor(Math.random()*C),type:types[Math.floor(Math.random()*types.length)],until:performance.now()+7000}}while(snake.some(p=>p.x===power.x&&p.y===power.y))}
function start(){reset();acc=0;last=performance.now();running=true;paused=false;$("overlay").classList.add("hidden");runs++;localStorage.runs=runs;requestAnimationFrame(loop);beep(660,.08)}
function end(){running=false;saveRun();best=Math.max(best,score);localStorage.neonBest=best;xp+=Math.max(5,score);localStorage.xp=xp;$("overlayTitle").textContent="RUN TERMINATED";$("overlayText").textContent="Score "+score+" • Best "+best+" • XP +"+Math.max(5,score);$("startBtn").textContent="RUN AGAIN";$("overlay").classList.remove("hidden");beep(120,.16);update()}
function setDir(x,y){if(x===-dir.x&&y===-dir.y)return;next={x,y};if(!running)start()}
function loop(now){if(!running)return;if(!paused){let interval=Math.max(42,speeds[diff]-(level-1)*7);acc+=now-last;while(acc>=interval){step();acc-=interval}draw()}last=now;requestAnimationFrame(loop)}
function step(){dir=next;let h={x:snake[0].x+dir.x,y:snake[0].y+dir.y};let ghost=power&&power.type==="GHOST"&&performance.now()<power.until;if(h.x<0||h.x>=C||h.y<0||h.y>=C){if(!ghost){end();return}}h.x=(h.x+C)%C;h.y=(h.y+C)%C;let hit=snake.some((p,i)=>i>0&&p.x===h.x&&p.y===h.y);if(hit&&!ghost){end();return}snake.unshift(h);if(food&&h.x===food.x&&h.y===food.y){let gain=food.type==="gold"?30:10;score+=gain;coins+=food.type==="gold"?3:1;level=1+Math.floor(score/100);xp+=2;beep(food.type==="gold"?900:620,.04);if(food.type==="power")spawnPower();spawnFood()}else snake.pop();if(power&&performance.now()>power.until)power=null;if(power&&h.x===power.x&&h.y===power.y){power.until=performance.now()+({OVERDRIVE:6000,SHIELD:8000,MAGNET:7000,GHOST:6000}[power.type]||6000);beep(800,.08)}update()}
function update(){$("score").textContent=String(score).padStart(4,"0");$("best").textContent=String(best).padStart(4,"0");$("level").textContent=level;$("coins").textContent=coins;$("xp").textContent=xp;$("runs").textContent=runs;$("xpbar").style.width=(xp%100)+"%"}
function grid(){ctx.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue("--grid");ctx.lineWidth=1;for(let i=0;i<=C;i++){ctx.beginPath();ctx.moveTo(i*S,0);ctx.lineTo(i*S,600);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*S);ctx.lineTo(600,i*S);ctx.stroke()}}
function glowRect(x,y,r,c){ctx.shadowBlur=18;ctx.shadowColor=c;ctx.fillStyle=c;ctx.fillRect(x*S+3,y*S+3,S-6,S-6);ctx.shadowBlur=0}
function draw(){ctx.clearRect(0,0,600,600);ctx.fillStyle=getComputedStyle(document.documentElement).getPropertyValue("--bg");ctx.fillRect(0,0,600,600);grid();if(food){let c=food.type==="gold"?"#f59e0b":food.type==="power"?"#a855f7":"#ff007f";ctx.beginPath();ctx.arc(food.x*S+12,food.y*S+12,food.type==="gold"?8:6,0,Math.PI*2);ctx.shadowBlur=20;ctx.shadowColor=c;ctx.fillStyle=c;ctx.fill();ctx.shadowBlur=0}if(power){let c="#00f3ff";ctx.beginPath();ctx.arc(power.x*S+12,power.y*S+12,9,0,Math.PI*2);ctx.strokeStyle=c;ctx.lineWidth=2;ctx.shadowBlur=16;ctx.shadowColor=c;ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle=c;ctx.font="12px sans-serif";ctx.textAlign="center";ctx.fillText("⚡",power.x*S+12,power.y*S+16)}snake.forEach((p,i)=>{let c=i===0?"#00f3ff":i<snake.length-1?"#00a8ff":"#0066cc";glowRect(p.x,p.y,c);if(i===0){ctx.fillStyle="#fff";ctx.fillRect(p.x*S+7,p.y*S+7,3,3);ctx.fillRect(p.x*S+14,p.y*S+7,3,3)}});if(paused){ctx.fillStyle="#030711bb";ctx.fillRect(0,0,600,600);ctx.fillStyle="#00f3ff";ctx.font="bold 28px monospace";ctx.textAlign="center";ctx.fillText("PAUSED",300,285);ctx.font="12px monospace";ctx.fillStyle="#94a3b8";ctx.fillText("Press P to resume",300,315)}}
$("startBtn").onclick=start;
document.querySelectorAll("[data-diff]").forEach(b=>b.onclick=()=>{diff=b.dataset.diff;document.querySelectorAll("[data-diff]").forEach(x=>x.classList.remove("active"));b.classList.add("active")});
$("soundBtn").onclick=()=>{sound=!sound;$("soundBtn").textContent=sound?"🔊":"🔇"};
$("themeBtn").onclick=()=>{ti=(ti+1)%themes.length;setTheme();draw()};
document.addEventListener("keydown",e=>{let k=e.key.toLowerCase();if(["arrowup","w"].includes(k)){e.preventDefault();setDir(0,-1)}else if(["arrowdown","s"].includes(k)){e.preventDefault();setDir(0,1)}else if(["arrowleft","a"].includes(k)){e.preventDefault();setDir(-1,0)}else if(["arrowright","d"].includes(k)){e.preventDefault();setDir(1,0)}else if(k==="p"&&running){paused=!paused;draw()}else if(k==="r"){start()}});
document.querySelectorAll(".mobile-controls button").forEach(b=>b.addEventListener("pointerdown",()=>{let d=b.dataset.dir;({up:()=>setDir(0,-1),down:()=>setDir(0,1),left:()=>setDir(-1,0),right:()=>setDir(1,0)})[d]()}));
canvas.addEventListener("pointerdown",e=>{canvas.setPointerCapture(e.pointerId);canvas._sx=e.clientX;canvas._sy=e.clientY});
canvas.addEventListener("pointerup",e=>{if(canvas._sx==null)return;let dx=e.clientX-canvas._sx,dy=e.clientY-canvas._sy;if(Math.max(Math.abs(dx),Math.abs(dy))>18){if(Math.abs(dx)>Math.abs(dy))setDir(Math.sign(dx),0);else setDir(0,Math.sign(dy))}canvas._sx=null});
setTheme();reset();renderLeaderboard();